-- Invoice.idempotencyKey — the column billingController already writes.
--
-- WHY THIS EXISTS AND WHY IT IS URGENT
-- `create()` in src/controllers/billingController.js writes
-- `idempotencyKey: idempotencyKey || null` on EVERY invoice, unconditionally —
-- not only when the client sends one. The field was added to schema.prisma and
-- the code shipped with it, but no migration was ever written, so a database
-- built purely from this migrations folder has no such column and every single
-- invoice insert fails with
--     Unknown argument `idempotencyKey`
-- That is not a degraded feature; it is all invoicing down — OPD consultation
-- auto-vouchers, pharmacy sales, lab and radiology billing, everything that
-- ends in an Invoice row.
--
-- WHAT THE COLUMN IS FOR
-- A double-clicked or retried "Create Invoice" used to produce a second bill
-- for the same visit, and the patient was charged twice. The client now sends a
-- token with the submit; if a row already carries that token the original
-- invoice is returned instead of a new one being created. The unique index is
-- what makes that safe under real concurrency: two simultaneous submits race to
-- insert, exactly one wins the index, and the loser catches P2002 and resolves
-- to the winner's row.
--
-- SCOPED PER ORGANISATION, like every other document key here. The token is
-- generated by one hospital's browser and means nothing in another's; a global
-- unique would let one tenant's token block another's insert. Same shape as
-- Payment.idempotencyKey, which got this treatment in
-- 20260708120000_add_payment_idempotency.
--
-- NULLABLE ON PURPOSE. Every existing invoice, and every future caller that
-- sends no token, stores NULL — and Postgres treats NULLs as distinct under a
-- unique index, so any number of rows may hold NULL without colliding. Nothing
-- is backfilled and no existing row is touched: this migration only adds a
-- column and an index.

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "idempotencyKey" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_organizationId_idempotencyKey_key"
ON "Invoice" ("organizationId", "idempotencyKey");
